# WWI dbt-partnership-demo
# Migrated from SSIS DailyETLMain.dtsx (WideWorldImporters → WideWorldImportersDW)
# All entities: City, Customer, Employee, Movement, Order, Payment Method, Purchase, Sale, Stock Holding, Stock Item, Supplier, Transaction, Transaction Type

name: 'dbt_partnership_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt_partnership_demo'

dbt-cloud:
  project-id: 70471823552417

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  wwi_source_dataset: "{{ env_var('WWI_SOURCE_DATASET', 'wide_world_importers') }}"
  wwi_dw_dataset: "{{ env_var('WWI_DW_DATASET', 'wide_world_importers_dw') }}"
  date_dim_start_year: 2013
  date_dim_end_year: "{{ var('date_dim_end_year', 2030) }}"
  # Optional: for incremental loads (SSIS LastETLCutoffTime / TargetETLCutoffTime)
  # Pass at run time: dbt run --vars '{"etl_cutoff_start": "2024-01-01 00:00:00", "etl_cutoff_end": "2024-01-02 00:00:00"}'
  etl_cutoff_start: "{{ var('etl_cutoff_start', '') }}"
  etl_cutoff_end: "{{ var('etl_cutoff_end', '') }}"
  # Optional: run identifier for lineage (replaces SSIS LineageKey). Set via --vars '{"run_id": "run_123"}'
  run_id: "{{ var('run_id', '') }}"

models:
  dbt_partnership_demo:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    dimensions:
      +schema: dimensions
      +materialized: table
    facts:
      +schema: facts
      +materialized: table
