# WWI dbt-partnership-demo
# Migrated from SSIS DailyETLMain.dtsx (WideWorldImporters → WideWorldImportersDW)
# All entities: City, Customer, Employee, Movement, Order, Payment Method, Purchase, Sale, Stock Holding, Stock Item, Supplier, Transaction, Transaction Type

name: 'dbt_partnership_demo'
version: '1.0.0'
config-version: 2

dbt-cloud:
  project-id: 70471823552417

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  wwi_source_dataset: "{{ env_var('WWI_SOURCE_DATASET', 'wide_world_importers') }}"
  wwi_dw_dataset: "{{ env_var('WWI_DW_DATASET', 'wide_world_importers_dw') }}"
  date_dim_start_year: 2013
  date_dim_end_year: "{{ var('date_dim_end_year', 2030) }}"

models:
  dbt_partnership_demo:
    # Staging & intermediate → dataset dbt_staging
    staging:
      +schema: dbt_staging
      +materialized: view
    intermediate:
      +schema: dbt_staging
      +materialized: view
    # Dimensions & facts → dataset dbt_target
    dimensions:
      +schema: dbt_target
      +materialized: table
    facts:
      +schema: dbt_target
      +materialized: table
