# Source: WideWorldImporters OLTP replicated to BigQuery (align identifiers to your replication)

version: 2
sources:
  - name: wwi_oltp
    description: WideWorldImporters transactional database
    database: "data-platforms-66d-demos"
    schema: dbt_source
    tables:
      - name: Cities
      - name: StateProvinces
      - name: Countries
      - name: Customers
      - name: CustomerCategories
      - name: BuyingGroups
      - name: People
      - name: PaymentMethods
      - name: StockItems
      - name: PackageTypes
      - name: Suppliers
      - name: SupplierCategories
      - name: TransactionTypes
      - name: Invoices
      - name: InvoiceLines
      - name: Orders
#        identifier: sales_orders
      - name: OrderLines
#        identifier: sales_order_lines
      - name: StockItemTransactions
#        identifier: warehouse_stock_item_transactions
      - name: PurchaseOrders
#        identifier: purchasing_purchase_orders
      - name: PurchaseOrderLines
#        identifier: purchasing_purchase_order_lines
      - name: CustomerTransactions
#        identifier: sales_customer_transactions
      - name: SupplierTransactions
#        identifier: purchasing_supplier_transactions
      - name: StockItemHoldings
