# Source: WideWorldImporters OLTP in BigQuery.
# - "name" = logical name used in SQL: source('wwi_oltp', 'Customers')
# - "identifier" = actual table name in BigQuery (must match your dataset).
# Set WWI_SOURCE_DATASET env var to the dataset where these tables live.

version: 2
sources:
  - name: wwi_oltp
    description: WideWorldImporters transactional database
    database: "data-platforms-66d-demos"
    schema: "dbt_source"
    tables:
      - name: Cities
        identifier: Cities
      - name: StateProvinces
        identifier: StateProvinces
      - name: Countries
        identifier: Countries
      - name: Customers
        identifier: Customers
      - name: CustomerCategories
        identifier: CustomerCategories
      - name: BuyingGroups
        identifier: BuyingGroups
      - name: People
        identifier: People
      - name: PaymentMethods
        identifier: PaymentMethods
      - name: StockItems
        identifier: StockItems
      - name: PackageTypes
        identifier: PackageTypes
      - name: Suppliers
        identifier: Suppliers
      - name: SupplierCategories
        identifier: SupplierCategories
      - name: TransactionTypes
        identifier: TransactionTypes
      - name: Invoices
        identifier: Invoices
      - name: InvoiceLines
        identifier: InvoiceLines
      - name: Orders
        identifier: Orders
      - name: OrderLines
        identifier: OrderLines
      - name: StockItemTransactions
        identifier: StockItemTransactions
      - name: PurchaseOrders
        identifier: PurchaseOrders
      - name: PurchaseOrderLines
        identifier: PurchaseOrderLines
      - name: CustomerTransactions
        identifier: CustomerTransactions
      - name: SupplierTransactions
        identifier: SupplierTransactions
      - name: StockItemHoldings
        identifier: StockItemHoldings
