# Source: WideWorldImporters OLTP replicated to BigQuery (align identifiers to your replication)

version: 2
sources:
  - name: wwi_oltp
    description: WideWorldImporters transactional database
    database: "data-platforms-66d-demos"
    schema: dbt_source
    tables:
      - name: Cities
<<<<<<< HEAD
      - name: StateProvinces
      - name: Countries
      - name: Customers
      - name: CustomerCategories
      - name: BuyingGroups
      - name: People
      - name: PaymentMethods
      - name: StockItems
      - name: PackageTypes
      - name: Suppliers
      - name: SupplierCategories
      - name: TransactionTypes
      - name: Invoices
      - name: InvoiceLines
      - name: Orders
#        identifier: sales_orders
      - name: OrderLines
#        identifier: sales_order_lines
      - name: StockItemTransactions
#        identifier: warehouse_stock_item_transactions
      - name: PurchaseOrders
#        identifier: purchasing_purchase_orders
      - name: PurchaseOrderLines
#        identifier: purchasing_purchase_order_lines
      - name: CustomerTransactions
#        identifier: sales_customer_transactions
      - name: SupplierTransactions
#        identifier: purchasing_supplier_transactions
      - name: StockItemHoldings
=======
        identifier: application_cities
      - name: StateProvinces
        identifier: application_state_provinces
      - name: Countries
        identifier: application_countries
      - name: Customers
        identifier: sales_customers
      - name: CustomerCategories
        identifier: sales_customer_categories
      - name: BuyingGroups
        identifier: sales_buying_groups
      - name: People
        identifier: application_people
      - name: PaymentMethods
        identifier: application_payment_methods
      - name: StockItems
        identifier: warehouse_stock_items
      - name: PackageTypes
        identifier: warehouse_package_types
      - name: Suppliers
        identifier: purchasing_suppliers
      - name: SupplierCategories
        identifier: purchasing_supplier_categories
      - name: TransactionTypes
        identifier: application_transaction_types
      - name: Invoices
        identifier: sales_invoices
      - name: InvoiceLines
        identifier: sales_invoice_lines
      - name: Orders
        identifier: sales_orders
      - name: OrderLines
        identifier: sales_order_lines
      - name: StockItemTransactions
        identifier: warehouse_stock_item_transactions
      - name: PurchaseOrders
        identifier: purchasing_purchase_orders
      - name: PurchaseOrderLines
        identifier: purchasing_purchase_order_lines
      - name: CustomerTransactions
        identifier: sales_customer_transactions
      - name: SupplierTransactions
        identifier: purchasing_supplier_transactions
      - name: StockItemHoldings
        identifier: warehouse_stock_item_holdings
>>>>>>> aa729c57a4de3ef4f25d7f5d8895df9672bb50dd
